import { expect, test } from '@playwright/test'

test('favorites persist independently of pins and legacy artwork, update search results, and work through Vim', async ({ page }) => {
  const api = (process.env.STARPALACE_TEST_API ?? 'http://127.0.0.1:7374/api/atlas')
  await page.goto('/')
  const search = page.getByRole('textbox', { name: 'Search library' })
  await search.fill('how places become memories')
  await page.getByRole('combobox', { name: 'Search mode' }).selectOption('exact')
  const result = page.locator('.atlas-result').first()
  await expect(result).toBeVisible()
  const id = await result.getAttribute('data-vim-file')
  expect(id).toBeTruthy()
  const original = await (await page.request.get(`${api}/file/${id}`)).json()
  try {
    await page.request.post(`${api}/file/${id}/favorite`, { data: { isFavorite: false, favoriteAppearance: 'pulsar' } })
    await result.click()
    const favorite = page.getByRole('button', { name: '☆ Favorite', exact: true })
    await expect(favorite).toBeVisible(); await favorite.click()
    await expect(page.getByRole('button', { name: '★ Unfavorite', exact: true })).toHaveAttribute('aria-pressed', 'true')
    await expect(result.getByLabel('Favorite', { exact: true })).toBeVisible()
    await page.getByRole('combobox', { name: 'Favorite appearance' }).selectOption('black-hole')
    await expect(page.getByRole('combobox', { name: 'Favorite appearance' })).toHaveValue('black-hole')
    await expect.poll(async () => (await (await page.request.get(`${api}/file/${id}`)).json()).favoriteAppearance).toBe('black-hole')
    const changed = await (await page.request.get(`${api}/file/${id}`)).json()
    expect(changed).toMatchObject({ isFavorite: true, favoriteAppearance: 'black-hole', isPinned: original.isPinned, x: original.x, y: original.y, starType: original.starType })
    await page.reload()
    await page.getByRole('button', { name: 'Show preview', exact: true }).click()
    await expect(page.getByRole('button', { name: '★ Unfavorite', exact: true })).toBeVisible()
    await expect(page.getByRole('combobox', { name: 'Favorite appearance' })).toHaveValue('black-hole')
    await page.locator('.atlas-context h1').click()
    await page.keyboard.press(':')
    await page.getByRole('textbox', { name: 'Vim command', exact: true }).fill('unfavorite')
    await page.getByRole('textbox', { name: 'Vim command', exact: true }).press('Enter')
    await expect(page.getByRole('button', { name: '☆ Favorite', exact: true })).toBeVisible()
    await page.keyboard.press(':')
    await page.getByRole('textbox', { name: 'Vim command', exact: true }).fill('favorite')
    await page.getByRole('textbox', { name: 'Vim command', exact: true }).press('Enter')
    await expect(page.getByRole('button', { name: '★ Unfavorite', exact: true })).toBeVisible()
    await expect(page.getByRole('combobox', { name: 'Favorite appearance' })).toHaveValue('black-hole')
    await page.getByRole('button', { name: 'List', exact: true }).click()
    const selected = page.locator(`.atlas-file-tile[data-vim-file="${id}"]`)
    await expect(selected.getByLabel('Favorite', { exact: true })).toBeVisible()
  } finally {
    await page.request.post(`${api}/file/${id}/favorite`, { data: { isFavorite: original.isFavorite ?? false, favoriteAppearance: original.favoriteAppearance ?? 'pulsar' } })
  }
})
