import { expect, test } from '@playwright/test'

test('the atlas starts without side panels and library visibility is remembered', async ({ page }) => {
  await page.goto('/')
  const map = page.locator('.atlas-map'), library = page.getByRole('navigation', { name: 'Library navigation' })
  await expect(map).toHaveAttribute('data-camera', /zoom/)
  await expect(library).toBeHidden()
  await expect(page.getByRole('complementary', { name: 'File reader' })).toHaveCount(0)
  await expect(page.getByRole('separator', { name: 'Reader width' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Show preview', exact: true })).toBeDisabled()
  const full = (await map.boundingBox())!, camera = await map.getAttribute('data-camera')
  expect(full.width).toBeGreaterThan(1400)
  await page.getByRole('button', { name: 'Show library', exact: true }).click()
  await expect(library).toBeVisible()
  await expect(page.getByRole('button', { name: 'Hide library', exact: true })).toHaveAttribute('aria-expanded', 'true')
  expect((await map.boundingBox())!.width).toBeLessThan(full.width - 150)
  await expect(map).toHaveAttribute('data-camera', camera!)
  await page.reload()
  await expect(library).toBeVisible()
  await page.getByRole('button', { name: 'Close library panel', exact: true }).click()
  await expect(library).toBeHidden()
  await page.reload()
  await expect(library).toBeHidden()
  await expect(page.getByRole('button', { name: 'Show library', exact: true })).toHaveAttribute('aria-expanded', 'false')
})

test('hiding the preview preserves selection, camera, and access to the expanded reader', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'List', exact: true }).click()
  const first = page.locator('.atlas-file-tile').first()
  await first.click()
  const id = await first.getAttribute('data-vim-file')
  await expect(page.getByRole('complementary', { name: 'File reader' })).toBeVisible()
  const title = await page.locator('.atlas-document-title').textContent()
  await page.getByRole('button', { name: 'Map', exact: true }).click()
  const map = page.locator('.atlas-map')
  await expect(map).toHaveAttribute('data-camera', /zoom/)
  const camera = await map.getAttribute('data-camera'), narrow = (await map.boundingBox())!.width
  await page.getByRole('button', { name: 'Close preview panel', exact: true }).click()
  await expect(page.getByRole('complementary', { name: 'File reader' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Show preview', exact: true })).toBeFocused()
  expect((await map.boundingBox())!.width).toBeGreaterThan(narrow + 300)
  await expect(map).toHaveAttribute('data-camera', camera!)
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('starpalace.atlas.selected')!))).toBe(id)
  await page.getByRole('button', { name: 'Show preview', exact: true }).click()
  await expect(page.locator('.atlas-document-title')).toHaveText(title!)
  await expect(page.locator('.atlas-reader-scroll')).toBeFocused()
  await expect(map).toHaveAttribute('data-camera', camera!)
  await page.getByRole('button', { name: 'Expand ↗', exact: true }).click()
  await expect(page.locator('.atlas-shell')).toHaveClass(/atlas-reading/)
  expect((await page.getByRole('complementary', { name: 'File reader' }).boundingBox())!.width).toBeGreaterThan(1400)
  await page.getByRole('button', { name: '↙ Back to atlas', exact: true }).click()
  await expect(map).toBeVisible()
  await page.getByRole('button', { name: 'Hide preview', exact: true }).click()
  await page.locator('.atlas-context h1').click()
  await page.keyboard.type(' l')
  await expect(page.locator('.atlas-reader-scroll')).toBeFocused()
  await page.reload()
  await expect(page.getByRole('complementary', { name: 'File reader' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Show preview', exact: true })).toBeEnabled()
})

test('small windows can show and dismiss each panel without horizontal overflow', async ({ page }) => {
  await page.setViewportSize({ width: 600, height: 800 })
  await page.goto('/')
  await page.getByRole('button', { name: 'Show library', exact: true }).click()
  await expect(page.getByRole('navigation', { name: 'Library navigation' })).toBeVisible()
  await page.getByRole('button', { name: 'Close library panel', exact: true }).click()
  await page.getByRole('button', { name: 'List', exact: true }).click()
  await page.locator('.atlas-file-tile').first().click()
  await expect(page.getByRole('complementary', { name: 'File reader' })).toBeVisible()
  await page.getByRole('button', { name: 'Close preview panel', exact: true }).click()
  await expect(page.locator('.atlas-file-browser')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(600)
})

test('search results collapse without clearing the query or moving the map', async ({ page }) => {
  await page.goto('/')
  const search = page.getByRole('textbox', { name: 'Search library' }), map = page.locator('.atlas-map')
  await search.fill('attention')
  await expect(page.locator('.atlas-result').first()).toBeVisible()
  const count = await page.locator('.atlas-result').count(), camera = await map.getAttribute('data-camera')
  await page.getByRole('button', { name: 'Close search results panel', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Search results' })).toHaveCount(0)
  await expect(search).toHaveValue('attention')
  await expect(map).toHaveAttribute('data-camera', camera!)
  await expect(page.getByRole('button', { name: 'Show search results', exact: true })).toBeFocused()
  await page.getByRole('button', { name: 'Show search results', exact: true }).click()
  await expect(page.locator('.atlas-result')).toHaveCount(count)
  await page.getByRole('button', { name: 'Hide search results', exact: true }).click()
  await search.fill('camera.ts')
  await expect(page.locator('.atlas-result').first()).toBeVisible()
  await page.getByRole('button', { name: 'Clear search', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Search results' })).toHaveCount(0)
})
