import { expect, test, type Page } from '@playwright/test'

async function list(page: Page) {
  await page.goto('/')
  await page.getByRole('button', { name: 'List', exact: true }).click()
  await expect(page.locator('.atlas-file-tile').first()).toBeVisible()
  await page.locator('.atlas-context h1').click()
}
async function ex(page: Page, text: string) {
  await page.keyboard.press(':')
  await page.getByRole('textbox', { name: 'Vim command', exact: true }).fill(text)
  await page.getByRole('textbox', { name: 'Vim command', exact: true }).press('Enter')
}

test('counts and grid/list boundaries move selection and visual ranges save exactly their members', async ({ page }) => {
  await list(page)
  const tiles = page.locator('.atlas-file-tile')
  await page.keyboard.type('gg2j')
  await expect(tiles.nth(2)).toHaveClass(/is-selected/)
  await page.keyboard.type('v2j')
  await expect(page.locator('.is-vim-selected')).toHaveCount(3)
  await expect(page.locator('.atlas-vim-status')).toContainText('VISUAL · 3 files')
  await ex(page, 'collection')
  await expect(page.getByRole('option', { name: 'Save 3 selected files' })).toHaveCount(1)
  await page.getByRole('button', { name: 'Close dialog', exact: true }).click()
  await page.keyboard.press('Escape')
  await expect(page.locator('.is-vim-selected')).toHaveCount(0)
  await page.keyboard.type('G')
  await expect(tiles.last()).toHaveClass(/is-selected/)
  await page.keyboard.type('4gg')
  await expect(tiles.nth(3)).toHaveClass(/is-selected/)
})

test('search typing and modal typing stay literal; Escape returns to navigation with search intact', async ({ page }) => {
  await list(page)
  await page.keyboard.press('/')
  const search = page.getByRole('textbox', { name: 'Search library' })
  await expect(search).toBeFocused()
  await search.fill('attention')
  await expect(page.locator('.atlas-file-tile').first()).toBeVisible()
  await search.press('Escape')
  await expect(search).toHaveValue('attention')
  await expect(search).not.toBeFocused()
  await page.keyboard.type('gg')
  await expect(page.locator('.atlas-file-tile').first()).toHaveClass(/is-selected/)
  await page.keyboard.press('Escape')
  await expect(search).toHaveValue('')
  await ex(page, 'help')
  await expect(page.getByRole('dialog')).toContainText('Vim browsing')
  await page.keyboard.press('Escape')
  await ex(page, 'not-a-command')
  await expect(page.getByRole('status')).toContainText('Unknown command')
})

test('marks and jump history return to files, and reader motions scroll instead of switching files', async ({ page }) => {
  await list(page)
  const tiles = page.locator('.atlas-file-tile')
  await page.keyboard.type('ggma5G')
  await expect(tiles.nth(4)).toHaveClass(/is-selected/)
  await page.keyboard.type("'a")
  await expect(tiles.first()).toHaveClass(/is-selected/)
  await page.keyboard.press('Control+o')
  await expect(tiles.nth(4)).toHaveClass(/is-selected/)
  await page.keyboard.press('Control+i')
  await expect(tiles.first()).toHaveClass(/is-selected/)
  await page.keyboard.press('/')
  const search = page.getByRole('textbox', { name: 'Search library' })
  await search.fill('copper lantern')
  await expect(page.locator('.atlas-file-tile').first()).toBeVisible()
  await search.press('Escape')
  await page.keyboard.type('gg')
  await page.keyboard.press('Enter')
  await expect(page.locator('.atlas-shell')).toHaveClass(/atlas-reading/)
  const reader = page.locator('.atlas-reader-scroll')
  await expect(page.locator('.atlas-reading-content')).toContainText('copper lantern')
  await page.keyboard.type('G')
  expect(await reader.evaluate(el => el.scrollTop)).toBeGreaterThan(100)
  await page.keyboard.type('gg')
  await expect.poll(() => reader.evaluate(el => el.scrollTop)).toBe(0)
})

test('native button activation and app search shortcuts survive Normal mode', async ({ page }) => {
  await list(page)
  const grid = page.getByRole('button', { name: 'Grid', exact: true })
  await grid.focus(); await page.keyboard.press('Space')
  await expect(grid).toHaveAttribute('aria-pressed', 'true')
  await page.keyboard.press('Control+f')
  await expect(page.getByRole('textbox', { name: 'Search library' })).toBeFocused()
  await page.getByRole('textbox', { name: 'Search library' }).press('Escape')
  await page.keyboard.type('gg')
  await page.keyboard.type('5G')
  await page.keyboard.type('10G')
  await page.keyboard.press('2'); await page.keyboard.press('Control+o')
  await expect(page.locator('.atlas-file-tile').first()).toHaveClass(/is-selected/)
  await page.keyboard.press('2'); await page.keyboard.press('Control+i')
  await expect(page.locator('.atlas-file-tile').nth(9)).toHaveClass(/is-selected/)
})
