import { chromium } from '@playwright/test'
import { mkdir } from 'node:fs/promises'

await mkdir('.atlas-dev/screenshots', { recursive: true })
const browser = await chromium.launch({ channel: 'chrome', headless: true })
const page = await browser.newPage({ viewport: { width: 1500, height: 1000 }, deviceScaleFactor: 2 })
page.setDefaultTimeout(10000)
const errors = []
page.on('pageerror', error => { errors.push(error.message); console.log('BROWSER ERROR:', error.stack) })
await page.goto('http://127.0.0.1:5174/', { waitUntil: 'networkidle' })
await page.screenshot({ path: '.atlas-dev/screenshots/overview.png' })
await page.getByRole('button', { name: 'Object guide', exact: true }).click()
await page.screenshot({ path: '.atlas-dev/screenshots/objects.png' })
await page.keyboard.press('Escape')
await page.locator('.atlas-region-nav button').first().click()
await page.getByRole('navigation', { name: 'Map destinations' }).getByRole('button').first().focus()
await page.keyboard.press('Enter')
await page.waitForTimeout(300)
await page.screenshot({ path: '.atlas-dev/screenshots/mixed-objects.png' })
await page.getByRole('navigation', { name: 'Map destinations' }).getByRole('button', { name: /Red giant/ }).first().focus()
await page.keyboard.press('Enter')
for (let i = 0; i < 8; i++) await page.getByRole('button', { name: 'Zoom in', exact: true }).click()
await page.waitForTimeout(250)
await page.screenshot({ path: '.atlas-dev/screenshots/close-up.png' })
await page.getByRole('button', { name: 'Star Palace home' }).click()
await page.getByRole('textbox', { name: 'Search library' }).fill('places become')
await page.getByRole('combobox', { name: 'Search mode' }).selectOption('exact')
await page.locator('.atlas-result').first().waitFor()
await page.locator('.atlas-result').first().click()
await page.locator('.atlas-reading-content h1').waitFor()
await page.screenshot({ path: '.atlas-dev/screenshots/search-preview.png' })
await page.getByRole('button', { name: 'Expand ↗', exact: true }).click()
await page.screenshot({ path: '.atlas-dev/screenshots/reader.png' })
console.log(JSON.stringify({ errors, title: await page.title(), screenshots: ['overview.png', 'search-preview.png', 'reader.png'] }, null, 2))
await browser.close()
