// Validates the graphics audit corpus harness — the lightweight test bed
// that materialises one cluster per star type so the renderer can be
// inspected against the original pitch deck without touching the user's
// real DB.
//
// The corpus is generated by `scripts/build-audit-corpus.mjs` and seeded
// into a daemon via `scripts/seed-audit.ts` (orchestrated by
// `scripts/dev-audit.sh`). This test guards the *contract* between those
// pieces:
//   - filename → star_type parsing in `parseAuditCorpusType`
//   - the constants (`AUDIT_PER_TYPE`, `AUDIT_TOTAL`) consumed by the
//     seed script's polling target
//   - if the audit corpus has been built locally, the directory contains
//     the expected number of files, each with a parseable name, and every
//     star type is covered the expected number of times.
//
// The third group is conditionally skipped: it's a smoke check for the
// generator script's output and only runs when `audit-corpus/` is present.

import { describe, expect, it } from 'vitest'
import { existsSync, readdirSync } from 'fs'
import { resolve } from 'path'
import {
  AUDIT_PER_TYPE,
  AUDIT_TOTAL,
  parseAuditCorpusType,
} from '../../src/shared/auditCorpus'
import { STAR_TYPES, type StarType } from '../../src/shared/types'

describe('auditCorpus constants', () => {
  it('AUDIT_TOTAL = STAR_TYPES.length × AUDIT_PER_TYPE', () => {
    expect(AUDIT_TOTAL).toBe(STAR_TYPES.length * AUDIT_PER_TYPE)
  })

  it('AUDIT_TOTAL crosses the layout threshold (200)', () => {
    // The seed script relies on the corpus being big enough to trigger
    // PCA training on first index; if this drops below 200 the renderer
    // ends up with layout_version=0 and skips every star.
    expect(AUDIT_TOTAL).toBeGreaterThanOrEqual(200)
  })
})

describe('parseAuditCorpusType', () => {
  it('parses every star type from a representative filename', () => {
    for (const t of STAR_TYPES) {
      expect(parseAuditCorpusType(`${t}-01.md`)).toBe(t)
      expect(parseAuditCorpusType(`${t}-21.md`)).toBe(t)
    }
  })

  it('rejects names that do not match <starType>-<NN>.md', () => {
    const bad = [
      'red-giant.md',
      'red-giant-1.md',     // single digit — generator pads to 02
      'red-giant-001.md',   // three digits — generator never emits this
      'red-giant-21.txt',
      'unknown-star-01.md',
      'something-else',
      '',
    ]
    for (const name of bad) {
      expect(parseAuditCorpusType(name)).toBeNull()
    }
  })
})

describe('audit-corpus/ directory (smoke — skipped if not built)', () => {
  const corpusDir = resolve(__dirname, '../../audit-corpus')
  const exists = existsSync(corpusDir)

  it.skipIf(!exists)('contains AUDIT_TOTAL files', () => {
    const files = readdirSync(corpusDir).filter(f => f.endsWith('.md'))
    expect(files.length).toBe(AUDIT_TOTAL)
  })

  it.skipIf(!exists)('every file parses to a known star type', () => {
    const files = readdirSync(corpusDir).filter(f => f.endsWith('.md'))
    const unknown = files.filter(f => parseAuditCorpusType(f) === null)
    expect(unknown).toEqual([])
  })

  it.skipIf(!exists)('each star type has AUDIT_PER_TYPE variants', () => {
    const files = readdirSync(corpusDir).filter(f => f.endsWith('.md'))
    const counts: Record<StarType, number> = Object.fromEntries(
      STAR_TYPES.map(t => [t, 0]),
    ) as Record<StarType, number>
    for (const f of files) {
      const t = parseAuditCorpusType(f)
      if (t) counts[t]++
    }
    for (const t of STAR_TYPES) {
      expect(counts[t], `expected ${AUDIT_PER_TYPE} ${t} files`).toBe(AUDIT_PER_TYPE)
    }
  })
})
